[package]
name = "android_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[profile.release]
strip = true
opt-level = 3
lto = "fat"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }

[dependencies]
